### ISSUE TITLE
The Deprotector freezes every time during the scanning for file names

### ISSUE THREAD

**Issue by SinisterLuffy5** [speige/WC3MapDeprotector#31]
I tried to use the Deprotector several times on the map in this link: https://xgm.guru/p/wc3/ACG-Arena-Original--l8.
The Deprotector hangs every time during the scanning.

**Comment by speige** [comment]
Are you using default options? (no checkboxes selected)

I tested on my PC with this map & it worked fine, no freezing. Maybe try leaving it overnight?
That's an extremely large map (file size 630MB), so that's probably why it's so slow.
It may also help to try on a faster PC, the program can become extremely slow if your PC runs out of RAM while scanning.

**Comment by SinisterLuffy5** [comment]
Yes, I was using the default options. Is there any way you can share the deprotected map or a listfile generated from the deprotected map?

**Comment by speige** [comment]
https://drive.google.com/file/d/16Kb6lDoKf760C8mnI4PdMjvXL_aU3D0S/view?usp=drive_link

Honestly, I don't think it's going to be very helpful for you. Although it opens in world editor, it has errors on save. It's an extremely big/complicated map, & the deprotector isn't perfect. Fixing it will probably take you a lot of work. Unless you're an expert map creator, I suggest starting with a simpler map.

If you just want to edit war3map.j, you don't need any deprotection at all. Just use MPQEditor with the protected map.
http://www.zezula.net/en/mpq/download.html

I have a tutorial video here explaining how to edit war3map.j directly:
https://youtu.be/Og1bGnSEoy8
