### ISSUE TITLE
Dragon Ball Random Defense 8.2

### ISSUE THREAD

**Issue by rfYami** [speige/WC3MapDeprotector#36]
Hey,

Im trying to deprotect Dragon Ball Random Defense 8.2 but it's not working somehow.

There are aboout 40 missing files after the scan which I should detect ingame while playing the map and i've done almost everything possible but im unable to find the missing files.

I want to update the Map myself with adding new Characters, Functions etc. but im unable to deprotect it.

Map - Link: https://maps.w3reforged.com/maps/categories/hero-defense-and-survival/PG%20DRD

**Comment by speige** [comment]
The 40 missing files is normal. It typically means it's a 3d model that was imported by the map creator but they never assigned it to a unit, so it's not actually needed. If you actually playtest the deprotected map & it's missing a 3d model, then you'll need to fix it yourself, but this is rare.

The biggest issue is that the war3map.j is not deprotecting into the triggers. This is strange, I haven't seen that before. I'll have to research to fix it. I'm a little busy with other projects right now, so I can't promise to get to it very quickly.

If you know c#, you can try to fix it yourself, all the source code is in this github repository.
Otherwise, you'll need to fix the map yourself using traditional manual deprotection techniques, like MPQEditor.
Or, you can always move on to a different map.

**Comment by rfYami** [comment]
Hey,

Thanks for the reply. Well im unable to play the the deprotected Map at all, 

also if i try to open it in the editor it always says they're some missing triggers.

**Comment by speige** [comment]
I've just released a new version of my tool, please try it out and see if it works better for you.
I can quick general advice over discord, my username is speige
I generally don't have time for custom requests, but if you want me to actually fix the problems for you, I can do it for a fee. My donation page is https://github.com/sponsors/speige

**Comment by speige** [comment]
I've just released a new version of my tool, please try it out and see if it works better for you.
I can quick general advice over discord, my username is speige
I generally don't have time for custom requests, but if you want me to actually fix the problems for you, I can do it for a fee. My donation page is https://github.com/sponsors/speige
